import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Self, cast

import tomlkit
import typer
from tomlkit.items import Table

from fedbench.runtime.registry import Group

app = typer.Typer()


@dataclass(frozen=True)
class _Component:
    group: Group
    name: str
    package: str

    @property
    def cls_name(self) -> str:
        return "".join(w.capitalize() for w in self.name.split("_"))

    @classmethod
    def parse(cls, arg: str) -> Self:
        try:
            group_keyword, qualifier = arg.split(":")
        except ValueError:
            raise typer.BadParameter("Syntax error, missing ':'.")
        try:
            group = Group(group_keyword)
        except ValueError:
            raise typer.BadParameter(f"Invalid group: {group_keyword}.")

        identifiers = qualifier.split(".")
        for ident in identifiers:
            if not ident.isidentifier():
                raise typer.BadParameter(
                    f"Syntax error, '{ident}' is not a valid identifier."
                )
        component = cls(group, identifiers[-1], ".".join(identifiers[:-1]))
        return component

    @classmethod
    def default(cls) -> Self:
        return cls(Group.SYNTHESIZERS, "my_synthesizer", "")


@app.command()
def new(
    name: Annotated[str, typer.Argument(help="Project name.")],
    components: Annotated[
        list[_Component] | None,
        typer.Argument(
            parser=_Component.parse,
            metavar="group:[identifier.]*identifier ...",
            help="Generate entry point declarations and scaffold "
            "implementations for supplied arguments. If no arguments, "
            "one Synthesizer is generated.",
        ),
    ] = None,
    root_dir: Annotated[
        Path | None, typer.Option(help="Project root directory.")
    ] = None,
) -> None:
    """Create a new plugin project.

    A plugin project can supply any number of components to any available
    entry point. If no root directory is provided, the current working directory
    is used. If the resolved root directory already contains a pyproject.toml,
    or any other file/directory that would be overwritten, the operation is aborted.
    """

    _root_dir = root_dir if root_dir else Path.cwd()
    _root_dir = _root_dir.resolve()
    _check_can_use_root_dir(_root_dir)

    if components is None:
        components = [_Component.default()]

    _generate_toml(name, cast(Iterable[_Component], components), _root_dir)

    project_dir = _root_dir.joinpath("src").joinpath(name)
    project_dir.mkdir(parents=True, exist_ok=False)


def _check_can_use_root_dir(root_dir: Path) -> None:
    if not root_dir.exists():
        print(f"No such directory: '{root_dir}'", file=sys.stderr)
        raise typer.Abort()

    if not root_dir.is_dir():
        print(f"Not a directory: '{root_dir}'", file=sys.stderr)
        raise typer.Abort()

    for child in sorted(root_dir.iterdir()):
        if child.name == "pyproject.toml":
            print(
                f"{root_dir.joinpath(child.name)} already exists. Can not create "
                f"a new project here.",
                file=sys.stderr,
            )
            raise typer.Abort()


def _generate_toml(
    name: str,
    components: Iterable[_Component],
    root_dir: Path,
) -> None:

    toml = tomlkit.document()
    toml.add(
        tomlkit.comment(f"Generated by {__name__} using tomlkit {tomlkit.__version__}")
    )
    project = tomlkit.table()
    project.add("name", name)
    project.add("version", "0.1.0")
    project.add("description", "")
    project.add("authors", tomlkit.array())
    project.add("license", "MIT")
    project.add(tomlkit.nl())
    project.add("dependencies", tomlkit.array())  # TODO! Add self dependency.

    entry_points = tomlkit.table()
    project.add("entry_points", entry_points)
    self_root = __name__.split(".")[0]

    for group in {c.group for c in components}:
        entry_points.add(f"{self_root}.{group.value}", tomlkit.table())

    for component in components:
        qualifier = f"{component.name.lower()}:{component.cls_name}"
        if component.package:
            qualifier = f"{component.package.lower()}.{qualifier}"

        ep: Table = cast(Table, entry_points[f"{self_root}.{component.group.value}"])
        ep.add(component.name, qualifier)

    toml.add("project", project)
    with root_dir.joinpath("pyproject.toml").open("w") as f:
        tomlkit.dump(toml, f)
