from pathlib import Path
from typing import Annotated

import tomlkit
import typer

from fedbench.runtime.registry import Group

app = typer.Typer()


@app.command(help="Create a new project for implementing pluggable components.")
def new(
    name: Annotated[str, typer.Argument(help="Project name.")],
    root_dir: Annotated[
        Path | None, typer.Option(help="Project root directory.")
    ] = None,
) -> None:

    _root_dir = root_dir if root_dir else Path.cwd()
    _root_dir = _root_dir.resolve()
    _check_can_use_root_dir(_root_dir)
    _generate_toml(_root_dir, project_name=name)


def _check_can_use_root_dir(root_dir: Path) -> None:
    if not root_dir.exists():
        raise FileNotFoundError(root_dir)

    if not root_dir.is_dir():
        raise NotADirectoryError(root_dir)

    # TODO! Look for pyproject.toml in parents?
    for child in root_dir.iterdir():
        if child.name in ("pyproject.toml", "src"):
            raise FileExistsError(
                f"{root_dir.joinpath(child.name)} already exists. Can not create "
                f"a new project here."
            )


def _generate_toml(root_dir: Path, project_name: str) -> None:
    toml = tomlkit.document()
    toml.add(
        tomlkit.comment(f"Generated by {__name__} using tomlkit {tomlkit.__version__}")
    )
    project = tomlkit.table()
    project.add("name", project_name)
    project.add("version", "0.1.0")
    project.add("description", "")
    project.add("authors", tomlkit.array())
    project.add("license", "MIT")
    project.add(tomlkit.nl())
    project.add("dependencies", tomlkit.array())  # TODO! Add self dependency.

    entry_points = tomlkit.table()
    project.add("entry_points", entry_points)
    for group in Group:
        entry_points.add(f"{__name__.split('.')[0]}.{group.value}", tomlkit.table())

    toml.add("project", project)
    with root_dir.joinpath("pyproject.toml").open("w") as f:
        tomlkit.dump(toml, f)
