from __future__ import annotations

import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Annotated, cast

import tomlkit
import typer
from tomlkit.items import Table
from tomlkit.toml_document import TOMLDocument

from fedbench.cli.plugin._component import _Component, codegen
from fedbench.cli.plugin._util import parse_identifier

app = typer.Typer()


@app.command()
def new(
    name: Annotated[
        str, typer.Argument(parser=_parse_project_name, help="Project name.")
    ],
    components: Annotated[
        list[_Component] | None,
        typer.Argument(
            parser=_Component.parse,
            metavar=f"{_Component.parser_syntax} ...",
            help="Generate entry point declarations and scaffold "
            "implementations for supplied arguments. If no arguments, "
            "one Synthesizer is generated.",
        ),
    ] = None,
    parent_dir: Annotated[Path | None, typer.Option()] = None,
) -> None:
    """Create a new plugin project.

    A plugin project can supply any number of components to any available
    entry point.
    """

    parent = parent_dir if parent_dir is not None else Path.cwd()
    parent = parent.resolve()

    root = parent.joinpath(name)
    if root.exists():
        print(f"{root} already exists.", file=sys.stderr)
        raise typer.Abort()

    root.mkdir()

    toml = _create_toml(name.lower(), components or (_Component.default(),))
    with root.joinpath("pyproject.toml").open("w") as f:
        tomlkit.dump(toml, f)

    pkg_root = root.joinpath("src").joinpath(name.lower())
    pkg_root.mkdir(parents=True, exist_ok=False)
    pkg_root.joinpath("__init__.py").touch()

    for component in components or (_Component.default(),):
        pkg = pkg_root
        for ident in component.module[:-1]:
            pkg = pkg.joinpath(ident)
            pkg.mkdir(exist_ok=True)
            pkg.joinpath("__init__.py").touch()

        srcfile = pkg.joinpath(component.name).with_suffix(".py")
        with srcfile.open("w") as f:
            f.write(codegen(component))


def _parse_project_name(project_name: str) -> str:
    parse_identifier(project_name.lower())
    return project_name


def _create_toml(project_name: str, components: Iterable[_Component]) -> TOMLDocument:
    def qualname(comp: _Component) -> str:
        return f"{'.'.join((project_name, *comp.module))}:{comp.class_name}"

    toml = tomlkit.document()
    toml.add(
        tomlkit.comment(f"Generated by {__name__} using tomlkit {tomlkit.__version__}")
    )
    project = tomlkit.table()
    project.add("name", project_name)
    project.add("version", "0.1.0")
    project.add("description", "")
    project.add("authors", tomlkit.array())
    project.add("license", "MIT")
    project.add(tomlkit.nl())
    project.add("dependencies", tomlkit.array())  # TODO! Add self dependency.

    entry_points = tomlkit.table()
    project.add("entry-points", entry_points)

    for group in {comp.group for comp in components}:
        entry_points.add(f"{group.entry_point}", tomlkit.table())

    for component in components:
        ep = cast(Table, entry_points[f"{component.group.entry_point}"])
        ep.add(component.name, qualname(component))

    toml.add("project", project)
    return toml
