 C4Container
     Container(plugin, "Plugin", "python package", "")
     Container_Boundary(framework, "Framework") {
         Container(main, "Application", "python package", "The framework main<br/>
            application.")
         Container_Ext(backend, "Simulation backend", "flwr", "Manages server/client
            threads/processes<br/> and executes framework defined <br>server/client
            logic.")
         Container(builtin, "Builtin", "python package/module", "Plugin or plugin
            like that comes bundled<br/> with the main app.")
     }
     ContainerDb_Ext(filesystem, "Local file system")

     Rel(plugin, main, "Provides component<br/>implementations")
     Rel(builtin, main, "Provides component<br/>implementations")
     Rel(main, backend, "Uses")
     Rel(main, filesystem, "Writes output to and reads dataset from")
     UpdateLayoutConfig($c4ShapeInRow="2")





