import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Annotated, cast

import tomlkit
import typer
from tomlkit.items import Table
from tomlkit.toml_document import TOMLDocument

from fedbench.cli.plugins._component import _Component, codegen, fully_qualified_name

app = typer.Typer()


@app.command()
def new(
    name: Annotated[str, typer.Argument(help="Project name.")],
    components: Annotated[
        list[_Component] | None,
        typer.Argument(
            parser=_Component.parse,
            metavar=f"{_Component.arg_syntax} ...",
            help="Generate entry point declarations and scaffold "
            "implementations for supplied arguments. If no arguments, "
            "one Synthesizer is generated.",
        ),
    ] = None,
) -> None:
    """Create a new plugin project under the current working directory.

    A plugin project can supply any number of components to any available
    entry point.
    """

    parent = Path.cwd()
    parent = parent.resolve()

    root = parent.joinpath(name)
    if root.exists():
        print(f"{root} already exists.", file=sys.stderr)
        raise typer.Abort()

    root.mkdir()

    if components is None:
        components = [_Component.default()]

    toml = _create_toml(name, cast(Iterable[_Component], components))
    with root.joinpath("pyproject.toml").open("w") as f:
        tomlkit.dump(toml, f)

    pkg_root = root.joinpath("src").joinpath(name.lower())
    pkg_root.mkdir(parents=True, exist_ok=False)
    pkg_root.joinpath("__init__.py").touch()

    for component in components:
        pkg = pkg_root.joinpath(component.group.value)
        pkg.mkdir(exist_ok=True)
        pkg.joinpath("__init__.py").touch()
        srcfile = pkg.joinpath(component.identifier.lower())
        with srcfile.open("w") as f:
            f.write(codegen(component))


def _create_toml(project_name: str, components: Iterable[_Component]) -> TOMLDocument:
    toml = tomlkit.document()
    toml.add(
        tomlkit.comment(f"Generated by {__name__} using tomlkit {tomlkit.__version__}")
    )
    project = tomlkit.table()
    project.add("name", project_name)
    project.add("version", "0.1.0")
    project.add("description", "")
    project.add("authors", tomlkit.array())
    project.add("license", "MIT")
    project.add(tomlkit.nl())
    project.add("dependencies", tomlkit.array())  # TODO! Add self dependency.

    entry_points = tomlkit.table()
    project.add("entry-points", entry_points)

    for group in {c.group for c in components}:
        entry_points.add(f"{group.entry_point}", tomlkit.table())

    for component in components:
        ep = cast(Table, entry_points[f"{component.group.entry_point}"])
        ep.add(component.identifier, fully_qualified_name(project_name, component))

    toml.add("project", project)
    return toml
