name: Release
on:
  push:
    tags: ['*']
permissions:
  contents: write
  actions: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Create GitHub release
        uses: docker://antonyurchenko/git-release@sha256:b1ef56a7ef18d23b7bd59efe10ddbfb9e38fa8cf644ef63c3cf5f2f64d70a32c  # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if echo "${{ github.ref_name }}" | grep -qE '(rc|alpha|beta|dev)'; then
            TARGET=testpypi
          else
            TARGET=pypi
          fi
          gh workflow run publish.yml --ref ${{ github.ref_name }} -f target=$TARGET