name: Release
on:
  push:
    tags: ['*']
permissions:
  contents: write
  actions: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create GitHub release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if echo "${{ github.ref_name }}" | grep -qE '(rc|alpha|beta|dev)'; then
            TARGET=testpypi
          else
            TARGET=pypi
          fi
          gh workflow run publish.yml --ref ${{ github.ref_name }} -f target=$TARGET